workspace:
    path: /Users/etiennemarais/Documents/workspace/Sites

environment:
    autoupdate: true

databases:
    valhalla:
        host: localhost
        database: valhalla
        username: root
        password:

images:
    - base