workspace:
    - /Users/etiennemarais/Documents/workspace/Sites

environment:
    autoupdate: false

databases:
    valhalla:
        host: localhost
        database: valhalla
        username: root
        password:

images:
    - base
    - data
    - phpfpm