#!/bin/bash

# Set base path to start of with
BASE_DIR=$( cd "$( dirname "$0" )" && pwd )

# Autoload all the /src files
for i in "${BASE_DIR}"/src/*.sh ; do
    if [ -f "$i" ]; then
        . $i
    fi
done

# Initialise the config file with variables
eval $(parseYaml "${BASE_DIR}"/config.yml "config_")

# Options to start the environment with
case $1 in
    start)
        outputInYellow "[Checking volume mount point]"
        if [ -z "${config_workspace}" ]; then
            error "Missing ${config_workspace} .. do you miss the config.yml file?"
        fi
        checkForVolumeMountpoint $config_workspace

        if [ "$config_environment_autoupdate" = "true" ]; then
            selfUpdateUsingGit
        fi

        for image in ${config_images[@]} ; do
            buildDockerImage $image
        done
    ;;
    *)
        exit_code=0
        if [ -z "$1" ]; then
          outputInRed "ERROR: Missing action to start Valhalla"
          exit_code=2
        fi

        # TODO Help needs to get shown here
        exit $exit_code
    ;;
esac